name: orders-service

on:
  push:
    branches: [main]
    paths:
      - 'services/orders-service/**'
  workflow_dispatch: {}
    
# id-token: write es lo que le permite a este workflow pedirle a AWS un token
# OIDC de corta duración en vez de usar un AWS_ACCESS_KEY_ID guardado en secrets.
permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-east-2
  ECR_REPOSITORY: repone-orders-service

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configurar credenciales AWS (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login a ECR
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v2

      - name: Configurar Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build y push de la imagen
        uses: docker/build-push-action@v6
        with:
          context: ./services/orders-service
          push: true
          cache-from: type=gha,scope=orders-service
          cache-to: type=gha,mode=max,scope=orders-service
          tags: |
            ${{ steps.ecr-login.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }}
   
  update-gitops:
    needs: build-and-push
    runs-on: ubuntu-latest
    concurrency:
      group: gitops-push
      cancel-in-progress: false
    steps:
      - name: Checkout repo gitops
        uses: actions/checkout@v4
        with:
          repository: AgustinLandriel/retail-inventory-gitops
          token: ${{ secrets.GITOPS_TOKEN }}
      - name: Actualizar tag de la imagen
        run: |
          yq -i '.image.tag = "${{ github.sha }}"' apps/repone-chart/values/orders-service.yaml
          
      - name: Commit y push de los cambios
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add apps/repone-chart/values/orders-service.yaml
          git commit -m "Actualizar tag de la imagen orders service a ${{ github.sha }}"
          git push    